@startuml IdentityComponent
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()

Container_Ext(androidApp, "Android Native App", "Kotlin / Jetpack Compose")
Container_Ext(flutterApp, "Cross-Platform App", "Flutter / Dart")
ContainerDb_Ext(mainDB, "SkillSwap Database", "MySQL 8")
System_Ext(emailService, "Email Api")

Container_Boundary(identityBC, "Identity & Access Bounded Context") {
    Component(identityController, "Identity Controller", "C# Class", "RESTful API Controller")
    Component(identityCommandService, "Identity CommandService", "C# Class", "Lógica de negocio")
    Component(identityQueryService, "Identity QueryService", "C# Class", "Consultas")
    Component(identityRepository, "Identity Repository", "C# Interface", "Interface persistencia")
    Component(emailExternal, "Email ExternalService", "C# Class", "Integración correo")
    Component(identityContextFacade, "Identity ContextFacade", "C# Class", "Punto de entrada interno")
}

Component_Ext(walletContextFacade, "Wallet ContextFacade", "C# Class", "Bounded Context: Wallet & Incentives")
Component_Ext(moderationContextFacade, "Moderation ContextFacade", "C# Class", "Bounded Context: Moderation & Disputes")

Component_Ext(assessmentQueryService, "Assessment QueryService", "C# Class", "Bounded Context: Assessment & Peer Review")
Component_Ext(reputationCommandService, "Reputation CommandService", "C# Class", "Bounded Context: Reputation")
Component_Ext(moderationQueryService, "Moderation QueryService", "C# Class", "Bounded Context: Moderation & Disputes")
Component_Ext(moderationCommandService, "Moderation CommandService", "C# Class", "Bounded Context: Moderation & Disputes")
Component_Ext(walletQueryService, "Wallet QueryService", "C# Class", "Bounded Context: Wallet & Incentives")

Rel(androidApp, identityController, "Request HTTP a Identity")
Rel(flutterApp, identityController, "Request HTTP a Identity")
Rel(identityController, identityCommandService, "Usa")
Rel(identityController, identityQueryService, "Usa")
Rel(identityCommandService, identityRepository, "Usa")
Rel(identityQueryService, identityRepository, "Usa")
Rel(identityRepository, mainDB, "SQL Transaction")

Rel(identityCommandService, emailExternal, "Delega envío")
Rel(emailExternal, emailService, "Enviar correo de validación")

Rel(identityCommandService, walletContextFacade, "Solicita la creación de la wallet inicial al registrarse")
Rel(identityQueryService, moderationContextFacade, "Pedir estado de sanción de la cuenta")

Rel(identityContextFacade, identityCommandService, "Delega")
Rel(identityContextFacade, identityQueryService, "Delega")

Rel(assessmentQueryService, identityContextFacade, "Pedir lista de Verificadores disponibles")
Rel(reputationCommandService, identityContextFacade, "Actualizar perfil con la nueva confiabilidad / Employability Score")
Rel(moderationQueryService, identityContextFacade, "Pedir datos de la cuenta reportada")
Rel(moderationCommandService, identityContextFacade, "Actualizar perfil en caso de sanción")
Rel(walletQueryService, identityContextFacade, "Confirmar biometría antes de canjear SkillCredits")

@enduml