@startuml SkillSwapContainer
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(student, "Estudiante", "Sube certificados, sigue su ruta de aprendizaje y demuestra sus habilidades.")
Person(verifier, "Verificador", "Revisa los casos que la IA no puede resolver con suficiente confianza, y supervisa la calidad del proceso de verificación.")

System_Boundary(skillSwapSystem, "SkillSwap Platform") {
    Container(landingPage, "Landing Page(estatica)", "HTML5 / CSS3 / JavaScript", "Sitio web estático que presenta el modelo de negocio de SkillSwap.")
    Container(androidApp, "Android Native Application", "Kotlin / Jetpack Compose", "Aplicación móvil nativa para Estudiantes y Verificadores.")
    Container(flutterApp, "Cross-Platform Application", "Flutter / Dart (dirigido a Android)", "Aplicación móvil multiplataforma para Estudiantes y Verificadores.")
    Container(apiGateway, "Api / RESTful Web Services", "ASP.NET Core (C#)", "Expone los endpoints del dominio, aplica las reglas de negocio y orquesta la lógica de los ocho Bounded Contexts.")
    ContainerDb(mainDB, "SkillSwap Database", "MySQL 8", "Base de datos única compartida por los ocho Bounded Contexts (skillswap_db)")
}

System_Ext(emailService, "Email Api", "Integración con correos institucionales")
System_Ext(mlKitService, "ML Kit (Firebase)", "SDK on-device de OCR/Entity Extraction")
System_Ext(cloudStorage, "Cloudinary", "Cloud Storage para certificados y evidencias")
System_Ext(stripeApi, "Stripe", "Procesamiento de pagos")

Rel(student, androidApp, "Usa")
Rel(verifier, androidApp, "Usa")
Rel(student, flutterApp, "Usa")
Rel(verifier, flutterApp, "Usa")

Rel(student, landingPage, "Visita")
Rel(verifier, landingPage, "Visita")

Rel(androidApp, apiGateway, "Consume API RESTful vía HTTPS")
Rel(flutterApp, apiGateway, "Consume API RESTful vía HTTPS")

Rel(apiGateway, mainDB, "Lee/Escribe")

Rel(apiGateway, emailService, "Envía correo de validación / notificación de sanción o disputa")
Rel(apiGateway, mlKitService, "Extrae datos del certificado (OCR on-device)")
Rel(apiGateway, cloudStorage, "Guarda certificados y evidencias adjuntas a un caso")
Rel(apiGateway, stripeApi, "Procesa el cobro de la suscripción")

@enduml